export default [
    {
        id: 1,
        address: "65 Front St W, Toronto, ON",
        type: "Public restroom",
        location: "Next to Uncle Tetsu in food court",
        hours: "8am-10pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 5,
        location_id: 1,
        likes: 8,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646830",
        lng: "-79.378520",
        sample: true
    },
    {
        id: 2,
        address: "55 Front St W, Toronto, ON",
        type: "Public restroom",
        location: "East entrance to York GO Station",
        hours: "9am-5pm",
        public_access: false,
        wheelchair_accessible: true,
        cleanliness: 3,
        location_id: 1,
        likes: 3,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646324",
        lng: "-79.378305",
        sample: true
    },
    {
        id: 3,
        address: "50 Bay St, Toronto, ON",
        type: "Coffee shop restroom",
        location: "CIBC Square Food Court",
        hours: "7am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 1,
        likes: 12,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646659",
        lng: "-79.378521",
        sample: true
    },
    {
        id: 4,
        address: "40 Bay St, Toronto, ON",
        type: "Public restroom",
        location: "Scotiabank Arena west entrance",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 1,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.643935",
        lng: "-79.378030",
        sample: true
    },
    {
        id: 5,
        address: "55 Front St W, Toronto, ON",
        type: "Public restroom",
        location: "The Alley west end",
        hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 1,
        likes: 5,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646624",
        lng: "-79.378505",
        sample: true
    },
    {
        id: 6,
        address: "55 Front St W, Toronto, ON",
        type: "Public Restroom",
        location: "Patties Express east side",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 1,
        likes: 9,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646924",
        lng: "-79.378105",
        sample: true
    },
    {
        id: 7,
        address: "65 Front St W, Toronto, ON",
        type: "Public Restroom",
        location: "Opposite of Kibo Market",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        location_id: 1,
        likes: 2,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646230",
        lng: "-79.378920",
        sample: true
    },
    {
        id: 8,
        address: "65 Front St W, Toronto, ON",
        type: "Public Restroom",
        location: "Shanghai 360",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 1,
        likes: 7,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.646430",
        lng: "-79.378220",
        sample: true
    },
    {
        id: 9,
        address: "161 Yorkville Ave, Toronto, ON",
        type: "Store Washroom",
        location: "Inside Delysees",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 2,
        likes: 10,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.670472",
        lng: "-79.391464",
        sample: true
    },
    {
        id: 10,
        address: "1240 Bay St, Toronto, ON",
        type: "Public Transit Restroom",
        location: "Bay TTC southside entrance",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 2,
        likes: 4,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.669735",
        lng: "-79.393684",
        sample: true
    },
    {
        id: 11,
        address: "142 Cumberland St, Toronto, ON",
        type: "Restaurant Restroom",
        location: "Hemingway's Restaurant and Bar",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 2,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.670520",
        lng: "-79.391660",
        sample: true
    },
    {
        id: 12,
        address: "55 Avenue Rd, Toronto, ON",
        type: "School restroom",
        location: "Equinox Yorkville",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 2,
        likes: 8,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.670240",
        lng: "-79.393960",
        sample: true
    },
    {
        id: 13,
        address: "98 Yorkville Ave, Toronto, ON",
        type: "Clothing store restroom",
        location: "Chanel Store",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 2,
        likes: 7,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.670625",
        lng: "-79.392475",
        sample: true
    },
    {
        id: 14,
        address: "101 Yorkville Ave, Toronto, ON",
        type: "Store restroom",
        location: "Axe & Hatchet Grooming Club",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        location_id: 2,
        likes: 9,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.670815",
        lng: "-79.392320",
        sample: true
    },
    {
        id: 15,
        address: "78 Yorkville Ave, Toronto, ON",
        type: "Clothing store restroom",
        location: "Kith Toronto",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 2,
        likes: 5,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.670950",
        lng: "-79.392250",
        sample: true
    },
    {
        id: 16,
        address: "1300 Bay St, Toronto, ON",
        type: "Boutique Restroom",
        location: "Inside Kim Du Salon",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 2,
        likes: 6,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.670065",
        lng: "-79.410295",
        sample: true
    },
    {
        id: 17,
        address: "75 Yorkville Ave, Toronto, ON",
        type: "Restaurant Restroom",
        location: "Inside Trattoria Nervosa",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 2,
        likes: 8,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.671000",
        lng: "-79.391700",
        sample: true
    },
    {
        id: 18,
        address: "72 Kensington Ave, Toronto, ON",
        type: "Restaurant Restroom",
        location: "Inside Seven Lives Tacos",
        hours: "8am-10pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 3,
        likes: 3,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.654225",
        lng: "-79.400625",
        sample: true
    },
	{
        id: 19,
        address: "5 Bellevue Ave, Toronto, ON",
        type: "Public Restroom",
        location: "Bellevue Square Park",
        hours: "9am-5pm",
        public_access: false,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 3,
        likes: 10,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.652810",
        lng: "-79.403600",
        sample: true
    },
    {
        id: 20,
        address: "5 Bellevue Ave, Toronto, ON",
        type: "Public Restroom",
        location: "Bellevue Square Park",
        hours: "7am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 3,
        likes: 4,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.652510",
        lng: "-79.403900",
        sample: true
    },
    {
        id: 21,
        address: "5 Bellevue Ave, Toronto, ON",
        type: "Public Restroom",
        location: "Bellevue Square Park",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 3,
        likes: 7,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.652210",
        lng: "-79.403300",
        sample: true
    },
    {
        id: 22,
        address: "207 Augusta Ave, Toronto, ON",
        type: "Restaurant Restroom",
        location: "Inside Knockout Chicken",
        hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 3,
        likes: 12,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.655580",
        lng: "-79.402610",
        sample: true
    },
    {
        id: 23,
        address: "56 Kensington Ave, Toronto, ON",
        type: "Convenience Store Restroom",
        location: "Inside Kensington Variety Convenience Store",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 3,
        likes: 5,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.654210",
        lng: "-79.400280",
        sample: true
    },
    {
        id: 24,
        address: "161 Baldwin St, Toronto, ON",
        type: "Clothing Store Restroom",
        location: "Inside vintage clothing store",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        location_id: 3,
        likes: 9,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.654960",
        lng: "-79.400690",
        sample: true
    },
    {
        id: 25,
        address: "244 Augusta Ave, Toronto, ON",
        type: "Bakery Shop Restroom",
        location: "Inside Bunner's Bakeshop",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 3,
        likes: 2,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.654170",
        lng: "-79.401330",
        sample: true
    },
    {
        id: 26,
        address: "55 Woodington Ave, Toronto, ON",
        type: "Public School Restroom",
        location: "Earl Beatty Junior and Senior Public School",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 4,
        likes: 6,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.696820",
        lng: "-79.314470",
        sample: true
    },
    {
        id: 27,
        address: "455 Glebeholme Blvd, Toronto, ON",
        type: "Community Centre Restroom",
        location: "Earl Beatty Community Centre",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 4,
        likes: 8,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.700930",
        lng: "-79.313440",
        sample: true
    },
    {
        id: 28,
        address: "438 Strathmore Blvd, Toronto, ON",
        type: "Gym restroom",
        location: "East York Personal Training Inc",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 4,
        likes: 5,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.694800",
        lng: "-79.318660",
        sample: true
    },
    {
        id: 29,
        address: "346 Strathmore Blvd, Toronto, ON",
        type: "Church Restroom",
        location: "Strathmore Boulevard Church of Christ",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 4,
        likes: 3,
        gender_neutral: false,
        family_friendly: false,
        lat: "43.693390",
        lng: "-79.319890",
        sample: true
    },
    {
        id: 30,
        address: "200 Wolverleigh Blvd, Toronto, ON",
        type: "Church Restroom",
        location: "Inside Kimbourne Park United Church",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 4,
        likes: 11,
        gender_neutral: true,
        family_friendly: false,
        lat: "43.692860",
        lng: "-79.315580",
        sample: true
    },
    {
        id: 31,
        address: "361 Glebeholme Blvd, Toronto, ON",
        type: "Studio Restroom",
        location: "Pegasus Studios",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        location_id: 4,
        likes: 7,
        gender_neutral: true,
        family_friendly: false,
        lat: "43.700000",
        lng: "-79.312390",
        sample: true
    },
    {
        id: 32,
        address: "790 Queen St W, Toronto, ON",
        type: "Public Restroom",
        location: "Trinity Bellwoods Park",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 5,
        likes: 4,
        gender_neutral: true,
        family_friendly: true,
        lat: "43.647960",
        lng: "-79.413170",
        sample: true
    },
    {
        id: 33,
        address: "790 Queen St W, Toronto, ON",
        type: "Public Restroom",
        location: "Trinity Bellwoods Park",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 5,
        likes: 9,
        gender_neutral: true,
        family_friendly: true,
        lat: "43.647660",
        lng: "-79.413470",
        sample: true
    },
    {
        id: 34,
        address: "790 Queen St W, Toronto, ON",
        type: "Public Restroom",
        location: "Trinity Bellwoods Park",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 5,
        likes: 5,
        gender_neutral: true,
        family_friendly: true,
        lat: "43.647360",
        lng: "-79.412870",
        sample: true
    },
    {
        id: 35,
        address: "790 Queen St W, Toronto, ON",
        type: "Public Restroom",
        location: "Trinity Bellwoods Park",
        hours: "8am-10pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 5,
        likes: 10,
        gender_neutral: true,
        family_friendly: true,
        lat: "43.647060",
        lng: "-79.413770",
        sample: true
    },
    {
        id: 36,
        address: "790 Queen St W, Toronto, ON",
        type: "Public Restroom",
        location: "Trinity Bellwoods Park",
        hours: "9am-5pm",
        public_access: false,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 5,
        likes: 8,
        gender_neutral: true,
        family_friendly: true,
        lat: "43.646760",
        lng: "-79.412570",
        sample: true
    },
    {
        id: 37,
        address: "155 Crawford St, Toronto, ON",
        type: "Community Centre Restroom",
        location: "155 Crawford St",
        hours: "7am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 5,
        likes: 2,
        gender_neutral: true,
        family_friendly: true,
        lat: "43.651360",
        lng: "-79.404040",
        sample: true
    },
    {
        id: 38,
        address: "227 A Crawford St, Toronto, ON",
        type: "Public Restroom",
        location: "Toronto Heritage Plaque: St. Hilda's College 1899",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 5,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.652990",
        lng: "-79.404020",
        sample: true
    },
    {
        id: 39,
        address: "298 Crawford St, Toronto, ON",
        type: "Public Restroom",
        location: "Toronto Hiking and Conservation Club",
        hours: "6am-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 5,
        likes: 12,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.652390",
        lng: "-79.403240",
        sample: true
    },
    {
        id: 40,
        address: "144 Gore Vale Ave, Toronto, ON",
        type: "Public Restroom",
        location: "Trinity Bellwoods Park Tennis Courts",
        hours: "9am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 5,
        likes: 5,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.647300",
        lng: "-79.413410",
        sample: true
    },
    {
        id: 41,
        address: "611 College St, Toronto, ON",
        type: "Restaurant Restroom",
        location: "Inside Danny's Pizza Tavern",
        hours: "5pm-2am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 2,
        location_id: 9,
        likes: 9,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.655130",
        lng: "-79.415010",
        sample: true
    },
    {
        id: 42,
        address: "713 College St, Toronto, ON",
        type: "Restaurant restroom",
        location: "Inside Kiss My Pans",
        hours: "11am-11pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 9,
        likes: 7,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.654410",
        lng: "-79.418130",
        sample: true
    },
    {
        id: 43,
        address: "559 College St, Toronto, ON",
        type: "Public Restroom",
        location: "Inside Service Canada Centre",
        hours: "10am-8pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 9,
        likes: 3,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.655290",
        lng: "-79.414680",
        sample: true
    },
    {
        id: 44,
        address: "540 College St, Toronto, ON",
        type: "Cafe Restroom",
        location: "Inside Little Pebbles Cafe",
        hours: "24 hours",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 9,
        likes: 11,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.655040",
        lng: "-79.414890",
        sample: true
    },
    {
        id: 45,
        address: "80 Clinton St, Toronto, ON",
        type: "School Restroom",
        location: "Saint Francis of Assisi Separate School",
        hours: "8am-6pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 9,
        likes: 6,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.650700",
        lng: "-79.418080",
        sample: true
    },
    {
        id: 46,
        address: "285 Colborne Lodge Dr, Toronto, ON",
        type: "Public Restroom",
        location: "Next to Lesya Ukrainka Monument",
        hours: "8am-4pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 12,
        likes: 8,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.650930",
        lng: "-79.463750",
        sample: true
    },
    {
        id: 47,
        address: "285 Colborne Lodge Dr, Toronto, ON",
        type: "Public Restroom",
        location: "High Park Picnic Site",
        hours: "12pm-12am",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 3,
        location_id: 12,
        likes: 4,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.651520",
        lng: "-79.463750",
        sample: true
    },
    {
        id: 48,
        address: "12 Trinity St, Toronto, ON",
        type: "Public Restroom",
        location: "Spirit of York Distillery Co",
        hours: "10am-6pm",
        public_access: true,
        wheelchair_accessible: false,
        cleanliness: 4,
        location_id: 13,
        likes: 10,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.650780",
        lng: "-79.357150",
        sample: true
    },
    {
        id: 49,
        address: "32 Tank House Lane, Toronto, ON",
        type: "Restaurant Restroom",
        location: "SOMA chocolatemaker",
        hours: "9am-7pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 5,
        location_id: 13,
        likes: 2,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.650630",
        lng: "-79.358310",
        sample: true
    },
    {
        id: 50,
        address: "51 Gristmill Lane, Toronto, ON",
        type: "Public Restroom",
        location: "The Distillery Winter Village",
        hours: "7am-9pm",
        public_access: true,
        wheelchair_accessible: true,
        cleanliness: 4,
        location_id: 13,
        likes: 7,
        gender_neutral: false,
        family_friendly: true,
        lat: "43.650630",
        lng: "-79.358200",
        sample: true
    }
];
